spring.application.name=api-gateway-service
server.port=8000

# Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Critical for lb:// to work
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Product Service Route
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
# Match /products AND /products/anything
spring.cloud.gateway.routes[0].predicates[0]=Path=/products,/products/**

# Exposure for checking routes
management.endpoints.web.exposure.include=gateway

# Order Service Route
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders,/orders/**

# CORS Configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*